# Generated by Django 3.0.6 on 2020-08-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('u_pass', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=20)),
            ],
        ),
    ]
