# Generated by Django 3.0.6 on 2020-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nissyou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question2',
            name='q2_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question2',
            name='q2_qid2',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='question2',
            name='q2_title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
