# Generated by Django 3.0.6 on 2020-08-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nissyou', '0002_auto_20200807_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question2',
            name='q2_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question2',
            name='q2_qid2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='question2',
            name='q2_title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
